spring.application.name=Samvaad

server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/samvaad_db
spring.datasource.username=root
spring.datasource.password=7388@Devy

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=TXlTdXBlclNlY3JldEtleUZvclNhbXZhYWRBcHBsaWNhdGlvbjIwMjZEZXZlbG9wbWVudA==
jwt.expiration=86400000